### ISSUE TITLE
Can not connect to server

### ISSUE THREAD

**Issue by meersonv** [geoglows/pygeoglows#43]
I'm not sure if my problem is related to the my simple python code:

**import geoglows
river_id_list = [210004000,210006110,210006111,]
forecast_data = geoglows.data.forecast (river_id_list, date='20241215', format='df', data_source='aws')**

I get the following output:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.9/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1120, in _create_connection_transport
    await waiter
  File "/usr/lib64/python3.9/asyncio/sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib64/python3.9/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.9/ssl.py", line 945, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1147)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiobotocore/httpsession.py", line 208, in send
    response = await self._session.request(
  File "/usr/local/lib64/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib64/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib64/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib64/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib64/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib64/python3.9/site-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host geoglows-v2-forecasts.s3.us-west-2.amazonaws.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1147)')]

Is the problem on my side or on the AWS server side?

Thank you,
Vladimir

**Comment by rileyhales** [comment]
Hi Vladimir. It looks like your code was unable to connect to the bucket. Probably because a certificate expired or was inaccessible. The AWS buckets do occasionally have temporary outages. I'm not able to reproduce the error after trying on multiple machines. Does it work for you now? It may have been a temporary outage that is now resolved.

**Comment by meersonv** [comment]
Hi Riley,
Thank you for the quick answer.
I found a solution here:

https://community.openai.com/t/ssl-certificate-verify-failed-certificate-verify-failed-self-signed-certificate-in-certificate-chain/705003/6

I put the following variables in my environment

**export SSL_CERT_FILE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
export REQUESTS_CA_BUNDLE=/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem**

and now everything works.

**Comment by msouff** [comment]
@meersonv I just want to clarify that getting our data doesn't require specifying certificates. AWS uses https but my understanding is that validation happens using default settings.

My guess is that your system was missing standard certificate settings or had an issue with SSL verification. Hence you had to set those variables manually.
